### ISSUE TITLE
能不能让主题支持无边框

### ISSUE THREAD

**Issue by Hentioe** [vinceliuice/vimix-kde#1]
目前 KDE 在用你的这个主题：https://github.com/vinceliuice/Qogir-kde

看上去你这个好像也不能无边框。如果没有边框的话，会美观许多，希望考虑。

**Comment by vinceliuice** [comment]
可以无边款,但是无边款之后,鼠标在边框处就无法进行放大缩小操作了,所以kde的窗口主题一般都保留边框,没有办法,kde的窗口管理底层功能有缺陷

**Comment by vinceliuice** [comment]
我也是很想去掉边款的,有些主题无边款确实更好,Qogir-kde我为了鼠标缩放可以操作都是尽量在底部保留了两个像素的边款,把左右两边的去掉了.

**Comment by Hentioe** [comment]
@vinceliuice 你好，我无意中发现 KDE 自带的微风主题，在无边框的情况下还能用鼠标正常缩放。这是否意味这有其它方法在响应无边框设置的情况下支持缩放。

我说的无边框是指的在这里的设置：

![image](https://user-images.githubusercontent.com/13946976/59038906-5bf14d00-88a6-11e9-8bea-95125ab230cb.png)

**Comment by vinceliuice** [comment]
我回去研究研究
