### ISSUE TITLE
Confused by the AUR packaging 

### ISSUE THREAD

**Issue by tiotrom** [vinceliuice/vimix-kde#2]
Is it this package https://aur.archlinux.org/pkgbase/vimix-kde-git/ or this package https://aur.archlinux.org/packages/kvantum-theme-vimix-git/ ? :D - I am making a custom Manjaro and I am confused to what I should include.

**Comment by vinceliuice** [comment]
vimix-kde-git have all themes that  kde plasma desktop need, and kvantum-theme-vimix only have kvantum themes I think

**Comment by Robosky** [comment]
> Is it this package https://aur.archlinux.org/pkgbase/vimix-kde-git/ or this package https://aur.archlinux.org/packages/kvantum-theme-vimix-git/ ? :D - I am making a custom Manjaro and I am confused to what I should include.

These two packages share the same package base. This means you can build them from the same PKGBUILD. I split it up, so that it can be consistent with official repo's adapta-kde and materia-kde.

**Comment by tiotrom** [comment]
Gotcha! Thanks!
