### ISSUE TITLE
AUTHORS

### ISSUE THREAD

**Issue by varlesh** [vinceliuice/vimix-kde#3]
Where my name on AUTHORS?

**Comment by varlesh** [comment]
You use my sources!!!

**Comment by varlesh** [comment]
It's your work, man?
![image](https://user-images.githubusercontent.com/8083855/57180748-88bfd800-6e94-11e9-815c-76faa9015ebd.png)

**Comment by varlesh** [comment]
https://github.com/PapirusDevelopmentTeam/materia-kde/blob/master/plasma/desktoptheme/Materia-Mono/icons/network.svg
https://github.com/vinceliuice/vimix-kde/blob/master/plasma/desktoptheme/Vimix/icons/network.svg

**Comment by vinceliuice** [comment]
I'm really sorry! Yesterday I was busy doing the vimix icon, forgetting to upload and modify, my fault!
Sorry about that
