### ISSUE TITLE
Pale media icon in tray

### ISSUE THREAD

**Issue by openmindead** [vinceliuice/vimix-kde#4]
Hi Vince, thank you for the great theme.

There's an issue with media icon in tray being barely visible:
![Screenshot_20190531_124201](https://user-images.githubusercontent.com/36324977/58678117-faab1480-83a1-11e9-802d-f4d576e1b6d7.png) 
![Screenshot_20190531_125633](https://user-images.githubusercontent.com/36324977/58678582-8ffad880-83a3-11e9-9c5b-9e9a2a317243.png)

If I manually replace media.svg with the original from Materia, it looks clearly visible:
![Screenshot_20190531_124240](https://user-images.githubusercontent.com/36324977/58678194-2b8b4980-83a2-11e9-9fcc-1ee96d485c31.png) 
![Screenshot_20190531_125719](https://user-images.githubusercontent.com/36324977/58678599-a6089900-83a3-11e9-9e81-381e5b5d0bc3.png)

This only applies to tray icon (pause, play), widget media control buttons are fine - white and visible on dark background. Player app doesn't matter (tried with Cantata and Google Play Music Desktop Player).

Oh, this is true for Canta theme as well if I remember correctly..

**Comment by openmindead** [comment]
Ah I see, Materia's svg has more icons including those that are necessary:
![Screenshot_20190531_125941](https://user-images.githubusercontent.com/36324977/58678772-4f4f8f00-83a4-11e9-9b73-0de09d8902c0.png)

**Comment by vinceliuice** [comment]
Thanks! I'll fix this
