### ISSUE TITLE
Aurorae theme colors not blending in well with Vimix dark beryl in Dolphin file manager.

### ISSUE THREAD

**Issue by freefreeno** [vinceliuice/vimix-kde#5]
There is a noticeable difference in color in Dolphin file manager from the title bar to the application itself. I know it is the same color so I guess it is just the gradient but I am not for sure. It actually looks like a different color but it is not. Also when you select Vimix dark beryl for your look and feel the color scheme does not change because you have the defaults wrong in the file. You have it this way.

[kdeglobals][General]
ColorScheme=Vimix-Dark-Beryl

It is because you have the look and feel and the color scheme two different names. The color scheme's name is:
 Vimix-Beryl-Dark 

and the look and feel name is 
Vimix-Dark-Beryl

You have listed like it has the same name. To fix it all you need to do is:

[kdeglobals][General]
ColorScheme=Vimix-Beryl-Dark

There may be more with the same problem but like I said I am on this one now.

**Comment by vinceliuice** [comment]
Thanks, I'll fix this

**Comment by vinceliuice** [comment]
Thanks, I'll fix this

**Comment by vinceliuice** [comment]
fixed

**Comment by freefreeno** [comment]
@vinceliuice  Ok thanks. If I find stuff I will let you know. I use some of your widgets in my themes and I appreciate that so much. I want so badly to learn how make my own widgets but I am having a hard time. I will report what I find. Any advice on learning to work svg's better??

**Comment by vinceliuice** [comment]
You just need time to practice using inkscape， I used inkscape more than 8 years, still I can't say    that I can use it skillfully. you just need more time to use it

**Comment by freefreeno** [comment]
Ok thanks. Yes inkscape is very daunting to say the least. I thought about taking a course or something.
